---
storage: :s3
s3_credentials:
  access_key_id: 19SQZEWB9DZFD5ZZ16R2
  secret_access_key: fTmq8Smd2WDBkLrh2v4wvTEAi3wGbfGVJ1JKSpvg
  bucket: flightseein
path: ":class/:id/:attachment/:style.:extension"
